function vectorfieldplot(path_des,Ts)

%  VECTORFIELDPLOT plots velocity and acceleration vector fields over and
%  assigned path. The input path_des is the struct output of the
%  trajectory.m program included with the DAMA^{ROB} toolbox. Ts is the
%  sampling time.
%  
%  syntax:
%       vectorfieldplot(path_des,Ts)
%
% Copyright (C) 2009, by Carmine Dario Bellicoso and Marco Caputano.
% This file is part of GNU LGPLv2.1 DAMA^{ROB}


%     DAMA^{ROB}: a symbolic robotics toolbox for matlab(tm)
%     Copyright (C) 2009, by Carmine Dario Bellicoso and Marco Caputano.
%       http://www.damarob.altervista.org
%       damarobotics@gmail.com
% 
%     This library is free software; you can redistribute it and/or
%     modify it under the terms of the GNU Lesser General Public
%     License as published by the Free Software Foundation; either
%     version 2.1 of the License, or (at your option) any later version.
% 
%     This library is distributed in the hope that it will be useful,
%     but WITHOUT ANY WARRANTY; without even the implied warranty of
%     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
%     Lesser General Public License for more details.
% 
%     You should have received a copy of the GNU Lesser General Public
%     License along with this library; if not, write to the Free Software
%     Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA



% Assignment of variables from the struct input
position = path_des.pos.signals.values;
velocity = path_des.pos_d.signals.values;
acceleration = path_des.pos_dd.signals.values;
attitude = path_des.attitude;


% Vector field will be plotted every n samples. Increase this value to show
% a less dense vector field, decrease it to show more of it.
n = ceil(1/4/Ts);

% Prepare a figure window
figure('Name','Planned trajectory in space','NumberTitle','off');

% Plot the assigned path
plot3(  position(:,1), ...
        position(:,2), ...
        position(:,3));
    
hold on;

%% Draw the trajectory with associated vector fields

% Plot the velocity vector field over the assigned path
quiver3(position(1:n:end,1), ...
        position(1:n:end,2), ...
        position(1:n:end,3), ...
        velocity(1:n:end,1), ...
        velocity(1:n:end,2), ...
        velocity(1:n:end,3));

% Plot the acceleration vector field over the assigned path
quiver3(position(1:n:end,1), ...
        position(1:n:end,2), ...
        position(1:n:end,3), ...
        acceleration(1:n:end,1), ...
        acceleration(1:n:end,2), ...
        acceleration(1:n:end,3));

% Plot start-point ('o') and end-point ('^') markers
plot3(  position(1,1), ...
        position(1,2), ...
        position(1,3), ...
        'MarkerSize',8,...
        'Marker','o',...
        'LineWidth',2,...
        'LineStyle','none');   

plot3(  position(end,1), ...
        position(end,2), ...
        position(end,3), ...
        'MarkerSize',8,...
        'Marker','^',...
        'LineWidth',2,...
        'LineStyle','none');     

    scale = 5;  
    
plot3([0  1/scale],...
      [0  0/scale],...
      [0  0/scale],...
      'r',...
      'Marker','^',...
      'MarkerSize',4,...
      'LineWidth',2);
  
plot3([0  0/scale],...
      [0  1/scale],...
      [0  0/scale],...
      'g',...
      'Marker','^',...
      'MarkerSize',4,...
      'LineWidth',2);
  
plot3([0  0/scale],...
      [0  0/scale],...
      [0  1/scale],...
      'b',...
      'Marker','^',...
      'MarkerSize',4,...
      'LineWidth',2);  
  
patch([-1 -1 1 1],[-1 1 1 -1],[0.76 0.57 0.48])

%% Draw reference frames where for changed orientation
    
for i = 1:length(attitude)
    or_x = attitude{i}.pos(1);
    or_y = attitude{i}.pos(2);
    or_z = attitude{i}.pos(3);

    
    % x
plot3([or_x  or_x+attitude{i}.R(1,1)/scale],...
      [or_y  or_y+attitude{i}.R(2,1)/scale],...
      [or_z  or_z+attitude{i}.R(3,1)/scale],...
      'r',...
      'Marker','^',...
      'MarkerSize',4,...
      'LineWidth',3);
    % y
plot3([or_x  or_x+attitude{i}.R(1,2)/scale],...
      [or_y  or_y+attitude{i}.R(2,2)/scale],...
      [or_z  or_z+attitude{i}.R(3,2)/scale],...
      'g',...
      'Marker','^',...
      'MarkerSize',4,...
      'LineWidth',3);
    % z
plot3([or_x  or_x+attitude{i}.R(1,3)/scale],...
      [or_y  or_y+attitude{i}.R(2,3)/scale],...
      [or_z  or_z+attitude{i}.R(3,3)/scale],...
      'b',...
      'Marker','^',...
      'MarkerSize',4,...
      'LineWidth',3);
    
end
    
grid;    

%% Show legend and axis labels on figure
legend('Path','Velocity','Acceleration','Start Point','End Point');
xlabel('x');
ylabel('y');
zlabel('z');
view([104.5 24]);

end
