function [figvr, vr_base] = createVR(manip)
% CREATEVR creates a VRML97 model of a manipulator.
%    syntax: [figvr, vr_base] = createVR(manip) 
% 
%  The program saves the VRML model in a file called nnnnnVR_base.wrl where
%  nnnnn is the manipulator's name.
%      vr_base: vrworld object associated with wrl file
%        figvr: vrfigure associated to vr_base
%
% Copyright (C) 2009, by Carmine Dario Bellicoso and Marco Caputano.
% This file is part of GNU LGPLv2.1 DAMA^{ROB}
%    http://www.damarob.altervista.org
%

%     DAMA^{ROB}: a symbolic robotics toolbox for matlab(tm)
%     Copyright (C) 2009, by Carmine Dario Bellicoso and Marco Caputano.
%       http://www.damarob.altervista.org
%       damarobotics@gmail.com
% 
%     This library is free software; you can redistribute it and/or
%     modify it under the terms of the GNU Lesser General Public
%     License as published by the Free Software Foundation; either
%     version 2.1 of the License, or (at your option) any later version.
% 
%     This library is distributed in the hope that it will be useful,
%     but WITHOUT ANY WARRANTY; without even the implied warranty of
%     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
%     Lesser General Public License for more details.
% 
%     You should have received a copy of the GNU Lesser General Public
%     License along with this library; if not, write to the Free Software
%     Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA

%% Main function
% evaluate workspace limits
lim = envelope(manip);

% extract revolute/prismatic information about joints
DH5 = char(manip.DH.table(:,5).'); 
DH5 = DH5(9:end-2);

background_RGB = [200, 225, 225];
background_RGB_1 = background_RGB./255;
DH = manip.DH.table;
Tb0 = manip.kin.T.Tb0;
Tne = manip.kin.T.Tne;
r = size(DH)*[1;0];
NL = [char(13),char(10)];
method = [manip.name,'VR_base'];

if exist([pwd,'/',method,'.wrl'],'file')
    delete([method,'.wrl']);
end

file_fun = fopen([method,'.wrl'],'a+');

alpha_base = atan2(Tb0(1,4),Tb0(2,4));
beta_base = atan2(Tb0(3,4),sqrt((Tb0(1,4)^2+Tb0(2,4)^2)));
[rbase_orient base_orient] = rot2aa(rotz(-alpha_base)*rotx(beta_base));
[rfirstT_vect firstT_rot] = rot2aa(Tb0(1:3,1:3));
           
% Start writing wrl file
fwrite(file_fun,[...
'#VRML V2.0 utf8',NL,...
'# Joints: ',DH5,NL,...
'DEF Base Transform',NL,...
'  {',NL,...
'   children ',NL,...
'     [',NL,...
'       Shape ',NL,...  % Base shape
'          {',NL,...
'            appearance Appearance ',NL,'{',NL,'material Material ',NL,'{',NL,'diffuseColor 0.650000 0.400000 0.300000',NL,'transparency 0.1',NL,'}',NL,'}',NL,...
'            geometry Box ',NL,'{',NL,'size ',num2str(lim(1,2)*2),' ',num2str(lim(2,2)*2),' 0.010000',NL,'}',NL,...
'          }',NL,...   % end Base shape
'       DEF Link0 Transform ',NL,...
'         {',NL,...
'         rotation ',num2str(rbase_orient(1)),' ',num2str(rbase_orient(2)),' ',num2str(rbase_orient(3)),' ',num2str(base_orient),' ',NL,...
'         translation ',num2str(Tb0(1,4)/2),' ',num2str(Tb0(2,4)/2),' ',num2str(Tb0(3,4)/2),NL,...
'         children ',NL,...
'            [',NL,...
'              Shape',NL,... % Link0 Shape
'                 {',NL,...
'                   appearance Appearance ',NL,'{',NL,'material Material ',NL,'{',NL,'diffuseColor 9.000001e-2 0.319999 0.444999',NL,'}',NL,'}',NL,...
'                   geometry Cylinder ',NL,'{',NL,'height ',num2str(sqrt(Tb0(1,4)^2+Tb0(2,4)^2+Tb0(3,4)^2)),NL,'radius 0.035000',NL,'}',NL,...
'                 }',NL,...  % end Link0 Shape
'                 ]',NL,...
'                 }',NL,...
'              DEF FirstT Transform ',NL,... % begin Frame 0
'                {',NL,...
'                rotation ',num2str(rfirstT_vect(1)),' ',num2str(rfirstT_vect(2)),' ',num2str(rfirstT_vect(3)),' ',num2str(firstT_rot),' ',NL,... % Pose of frame 0 with respect to Link0 center
'                translation ',num2str(Tb0(1,4)),' ',num2str(Tb0(2,4)),' ',num2str(Tb0(3,4)),NL,...
'                 children',NL,...
'                   [',NL]);
%num2str(sqrt(Tb0(1,4)^2+Tb0(2,4)^2+Tb0(3,4)^2))
% Insert a viewable reference frame for Frame 0              
               
insert_axis_z('0',file_fun);
insert_axis_y('0',file_fun);
insert_axis_x('0',file_fun);

% Recursive insertion of successive links
    if DH(1,5) == 0
        insert_joint_rot('1',DH,r,file_fun,Tne);
    else
        insert_joint_prism('1',DH,r,file_fun,Tne);
    end

% Append end part of file
fwrite(file_fun,[NL,...
']',NL,... % End Link0 child
'}',NL]);  % End Link0 transform

% Insert base axes
insert_axis_z('base',file_fun);
insert_axis_y('base',file_fun);
insert_axis_x('base',file_fun);

fwrite(file_fun,[NL,']',NL,... % End Base child
'}',NL]);                      % End Base transform

%% Define viewpoints
fwrite(file_fun,[NL,...
    'Background ',NL,...
'  {',NL,...
'  skyColor ',NL,...
'    [',NL,...
'    ',num2str(background_RGB_1),NL,...
'    ]',NL,...
'  }',NL,...
'',NL,...
'DEF STD Viewpoint',NL,...
'  {',NL,...
'  fieldOfView 0.500000',NL,...
'  orientation 0.350553 0.523699 0.776436 2.16305',NL,...
'  position ' num2str(1.37*[1.44 0.53 0.76]*norm(lim(:,2))),NL ... 3.54316 1.29216 1.86001
'  description "STD"',NL,...
'  }',NL,...
'DEF XY_plane Viewpoint',NL,...
'  {',NL,...
'  fieldOfView 9.999999e-3',NL,...
'  orientation 0 1 0 0',NL,...
'  position 0 0 ',num2str( 100*2*max(lim(1:2,2)) ),NL,...
'  description "XY_plane"',NL,...
'  }',NL,...
'',NL,...
'DEF XY_perspective Viewpoint ',NL,...
'  {',NL,...
'  fieldOfView 0.100000',NL,...
'  orientation 0 1 0 0',NL,...
'  position 0 0 ',num2str( 10*2*max(lim(1:2,2)) ),NL,...
'  description "XY_perspective"',NL,...
'  }',NL,...
'',NL,...
'DEF leftXZ Viewpoint ',NL,...
'  {',NL,...
'  fieldOfView 0.130000',NL,...
'  orientation 1 0 0 1.570000',NL,...
'  position 0 ', num2str(-10 * lim(3,2)),' ',num2str( lim(3,2)/2 ),NL,...
'  description "left view (XZ)"',NL,...
'  }',NL,...
'DEF rightXZ Viewpoint ',NL,...
'  {',NL,...
'  fieldOfView 0.130000',NL,...
'  orientation 0 0.7071 0.7071 3.14',NL,...
'  position 0 ', num2str(10 * lim(3,2)),' ',num2str(lim(3,2)/2 ),NL,...
'  description "right view (-XZ)"',NL,...
'  }',NL,...
'DEF rearYZ Viewpoint ',NL,...
'  {',NL,...
'  fieldOfView 0.130000',NL,...
'  orientation 0.5774 -0.5774 -0.5774 2.0944',NL,...
'  position ',num2str(-10 * lim(3,2) ),' 0 ', num2str(lim(3,2)/2),NL,...
'  description "rear view (-YZ)"',NL,...
'  }',NL,...
'DEF frontYZ Viewpoint ',NL,...
'  {',NL,...
'  fieldOfView 0.130000',NL,...
'  orientation 0.5774 0.5774 0.5774 2.0944',NL,...
'  position ',num2str(10 * lim(3,2) ),' 0 ', num2str(lim(3,2)/2),NL,...
'  description "front view (-YZ)"',NL,...
'  }',NL]);
  
fclose(file_fun);

% Add VR data to manipulator object
vr_base = vrworld([manip.name,'VR_base.wrl']);
set(vr_base', 'Description', ['DAMA manipulator: ',manip.name]);
open(vr_base);
figvr = view(vr_base);
image_capture = capture(figvr);
im_crop = cropimage(image_capture,background_RGB);
imagefile = [manip.name,'_3D.png'];
imwrite(im_crop,imagefile,'png');

% End main function
end

%% Insert prismatic joint

function insert_joint_prism(link_num,DH,r,file_fun,Tne)

i = str2double(link_num);
NL = [char(13),char(10)];
prism_link_length = 1;
z_num = str2double(link_num)-1;

% Start writing file...
fwrite(file_fun,[NL,...
'DEF Z' num2str(z_num) ' Transform',NL,...
' {',NL,...
'  rotation 0 0 1 ',num2str(double(DH(i,4))),NL,...
'  children',NL,... 
'   [',NL,...
'    DEF Joint' link_num ' Transform',NL,...
'      {',NL,...
'      rotation 1 0 0 1.5708',NL,...
'       children ',NL,...
'         [',NL,...
'          Shape ',NL,...
'           {',NL,...
'            appearance Appearance ',NL,'{',NL,'material Material ',NL,'{',NL,'diffuseColor 0.740000 0.529999 0.159999',NL,'}',NL,'}',NL,...
'            geometry Cylinder ',NL,'{',NL,'height 0.1',NL,'radius 0.045',NL,'}',NL,...
'           }',NL,...
'         ]',NL,...
'      }',NL,...
'    DEF Link' link_num ' Transform',NL,...
'      {',NL,...
'        translation 0 0 ', num2str(-prism_link_length/2+0.045),NL,...
'       children ',NL,...
'        [',NL,...
'         Shape ',NL,...
'           {',NL,...
'           appearance Appearance',NL,'{',NL,'material Material ',NL,'{',NL,'diffuseColor 9.000001e-2 0.319999 0.444999',NL,'}',NL,'}',NL,...
'           geometry Box ',NL,'{',NL,'size 0.060000 0.060000 ',num2str(prism_link_length),NL,'}',NL,...
'           }',NL,...
'         DEF NextT' link_num ' Transform',NL,...
'           {',NL,...
'           translation 0 0 ', num2str(prism_link_length/2) ,NL,...
'           rotation 1 0 0 ', num2str(double(DH(i,2))),NL,...
'           children',NL,'[',NL]);

if i < r
 insert_axis_z(link_num,file_fun);
 insert_axis_y(link_num,file_fun);
 insert_axis_x(link_num,file_fun);
end

if i == r && DH(r,1) ~= 0
 insert_axis_z(link_num,file_fun);
 insert_axis_y(link_num,file_fun);
 insert_axis_x(link_num,file_fun);
end

% Recursive insertion of remaining joints
if i<r
    next = str2double(link_num)+1;
    if DH(i+1,5) == 0
    insert_joint_rot(num2str(next),DH,r,file_fun,Tne);    % insert a revolute joint
    else
    insert_joint_prism(num2str(next),DH,r,file_fun,Tne);  % insert a prismatic joint
    end
end

%If the link is the last one, insert the end-effector
if i == r
    insert_end_effector(file_fun,Tne);
end

% Finish writing file...
fwrite(file_fun,[']',NL,... % End NextTi child
'}',NL,...
']',NL,... % End Linki child
'}',NL,...
']',NL,... % End Zi child
'}',NL]);

end

%% Insert revolute joint

function insert_joint_rot(link_num,DH,r,file_fun,Tne)

i = str2double(link_num);
NL = [char(13),char(10)];
z_num = str2double(link_num)-1;

% Start writing file...
fwrite(file_fun,[NL,...
'DEF Z' num2str(z_num) ' Transform',NL,...
' {',NL,...
'   children',NL,...
'    [',NL,...
'     DEF Joint' link_num ' Transform',NL,...
'       {',NL,...
'        rotation 1 0 0 1.5708',NL,...
'        translation 0 0 0',NL,...  % Pose of Joint i with respect to Zi transform
'        children',NL,...
'        [',NL,...
'           Shape',NL,... 
'            {',NL,...
'            appearance Appearance',NL,'{',NL,'material Material',NL,'{',NL,'diffuseColor 0.740000 0.529999 0.159999',NL,'}',NL,'}',NL,...
'            geometry Cylinder',NL,'{',NL,'height 0.1',NL,'radius 0.040000',NL,'}',NL,...
'            }',NL,...
'          DEF Link' link_num ' Transform',NL,...
'           {',NL,...
'            translation ', num2str(double(DH(i,1))/2) ,' 0 0',NL,...  % Pose of Link i with respect to Joint i
'            children',NL,...
'             [',NL,...
'              Shape',NL,...
'               {',NL,...
'               appearance Appearance',NL,'{',NL,'material Material ',NL,'{',NL,'diffuseColor 9.000001e-2 0.319999 0.444999',NL,'}',NL,'}',NL,...
'               geometry Box',NL,'{',NL,'size ', num2str(double(DH(i,1))) ,' 0.075000 0.075000',NL,'}',NL,...
'               }',NL,...
'                DEF Doffset Transform',NL,...
'                  {',NL,...
'                  rotation 1 0 1.5708 0',NL,...
'                  translation ',num2str(double(DH(i,1))/2),' ',num2str(double(DH(i,3))/2),' 0',NL,...
'                  children',...
'                   [',NL,...
'                    Shape',NL,...
'                     {',NL,...
'                     appearance Appearance',NL,'{',NL,'material Material ',NL,'{',NL,'diffuseColor 9.000001e-2 0.319999 0.444999',NL,'}',NL,'}',NL,...
'                     geometry Cylinder',NL,'{',NL,'height ', num2str(abs(double(DH(i,3)))) ,' radius 0.03',NL,'}',NL,...
'                     }',NL,...
'                    ]',NL,...
'                   }',NL,...
'                DEF NextT' link_num ' Transform',NL,...
'                  {',NL,...
'                  translation ', num2str(double(DH(i,1))/2) ,' ',num2str(double(DH(i,3))), ' 0',NL,...
'                  rotation -1 0 0 ',  num2str(-double(DH(i,2))+1.5708),NL,...
'                  children',NL,'[',NL]);
       
% Insert viewable axes for Frame i
if i < r
 insert_axis_z(link_num,file_fun);
 insert_axis_y(link_num,file_fun);
 insert_axis_x(link_num,file_fun);
end

if i == r && DH(r,1)~=0
 insert_axis_z(link_num,file_fun);
 insert_axis_y(link_num,file_fun);
 insert_axis_x(link_num,file_fun);
end

% Recursive insertion of remaining joints

if i < r
    next = str2double(link_num)+1;
    if DH(i+1,5) == 0
        insert_joint_rot(num2str(next),DH,r,file_fun,Tne);
    else
        insert_joint_prism(num2str(next),DH,r,file_fun,Tne);
    end
end

% If the link is the last one, insert the end-effector

if i == r
    insert_end_effector(file_fun,Tne);
end

% Finish writing file...

fwrite(file_fun,[']',NL,... % End NextT child
'}',NL,']',NL,... % End Linki child
'}',NL,']',NL,... % End Jointi child
'}',NL,']',NL,... % End Zi child
'}',NL]);

end

%% Insert Z axis

function insert_axis_z(link_num,file_fun)

NL = [char(13),char(10)];

% Start writing file...
fwrite(file_fun,[NL,...
'DEF Zaxis' link_num ' Transform',NL,... 
' {',NL,... 
'  rotation 1 0 0 1.5708',NL,... % Pose of Zaxis with respect to parent transform
'  translation 0 0 0.1',NL,...
'   children',NL,... 
'    [',NL,... 
'     Shape',NL,...
'      {',NL,... 
'      appearance Appearance',NL,'{',NL,'material Material',NL,'{',NL,'diffuseColor 0 0 1',NL,'}',NL,'}',NL,... 
'      geometry Cylinder',NL,'{',NL,'radius 4.000002e-3',NL,'height 0.2',NL,'}',NL,...
'      }',NL,...
'    DEF Zcone' link_num ' Transform',NL,...
'     {',NL,...
'     translation 0 0.1 0',NL,... % Pose of Zcone with respect to Zaxis
'       children',NL,... 
'        [',NL,...
'         Shape',NL,... 
'          {',NL,...
'          appearance Appearance',NL,'{',NL,'material Material',NL,'{',NL,'diffuseColor 0 0 1',NL,'}',NL,'}',NL,...
'          geometry Cone',NL,'{',NL,'bottomRadius 0.010000',NL,'height 0.020000',NL,'}',NL,...
'          }',NL,...
'        ]',NL,...
'      }',NL,...
'    ]',NL,...
'  }',NL]);

end

%% Insert Y axis

function insert_axis_y(link_num,file_fun)

NL = [char(13),char(10)];

% Start writing file...
fwrite(file_fun,[NL,...
'DEF Yaxis' link_num ' Transform',NL,... 
' {',NL,... 
'  translation 0 0.1 0',NL,... % Pose of Yaxis with respect to parent transform
'   children',NL,... 
'    [',NL,... 
'     Shape',NL,...
'      {',NL,... 
'      appearance Appearance',NL,'{',NL,'material Material',NL,'{',NL,'diffuseColor 0 1 0',NL,'}',NL,'}',NL,... 
'      geometry Cylinder',NL,'{',NL,'radius 4.000002e-3',NL,'height 0.2',NL,'}',NL,...
'      }',NL,...
'    DEF Ycone' link_num ' Transform',NL,...
'     {',NL,...
'     translation 0 0.1 0',NL,... % Pose of Ycone with respect to Yaxis
'       children',NL,... 
'        [',NL,...
'         Shape',NL,... 
'          {',NL,...
'          appearance Appearance',NL,'{',NL,'material Material',NL,'{',NL,'diffuseColor 0 1 0',NL,'}',NL,'}',NL,...
'          geometry Cone',NL,'{',NL,'bottomRadius 0.010000',NL,'height 0.020000',NL,'}',NL,...
'          }',NL,...
'        ]',NL,...
'      }',NL,...
'    ]',NL,...
'  }',NL]);

end

%% Insert X axis

function insert_axis_x(link_num,file_fun)

NL = [char(13),char(10)];

% Start writing file...
fwrite(file_fun,[NL,...
'DEF Xaxis' link_num ' Transform',NL,... 
' {',NL,... 
' rotation 0 0 1 -1.5708',NL,... % Pose of Xaxis with respect to parent transform
' translation 0.1 0 0',NL,...
'   children',NL,... 
'    [',NL,... 
'     Shape',NL,...
'      {',NL,... 
'      appearance Appearance',NL,'{',NL,'material Material',NL,'{',NL,'diffuseColor 1 0 0',NL,'}',NL,'}',NL,... 
'      geometry Cylinder',NL,'{',NL,'radius 4.000002e-3',NL,'height 0.2',NL,'}',NL,...
'      }',NL,...
'    DEF Xcone' link_num ' Transform',NL,...
'     {',NL,...
'     translation 0 0.1 0',NL,... % Pose of Xcone with respect to Xaxis
'       children',NL,... 
'        [',NL,...
'         Shape',NL,... 
'          {',NL,...
'          appearance Appearance',NL,'{',NL,'material Material',NL,'{',NL,'diffuseColor 1 0 0',NL,'}',NL,'}',NL,...
'          geometry Cone',NL,'{',NL,'bottomRadius 0.010000',NL,'height 0.020000',NL,'}',NL,...
'          }',NL,...
'        ]',NL,...
'      }',NL,...
'    ]',NL,...
'  }',NL]);

end

%% Insert End-Effector

function insert_end_effector(file_fun,Tne)

NL = [char(13),char(10)];
[r_vect rot] = rot2aa(Tne(1:3,1:3));

alpha = atan2(Tne(1,4),Tne(2,4));
beta = atan2(Tne(3,4),sqrt((Tne(1,4)^2+Tne(2,4)^2)));
[r_orient orient] = rot2aa(rotz(-alpha)*rotx(beta));

fwrite(file_fun,[NL,...
'DEF Doffset_ee Transform',NL,...
'           {',NL,...
'           rotation ',num2str(r_orient(1)),' ',num2str(r_orient(2)),' ',num2str(r_orient(3)),' ',num2str(orient),' ',NL,...
'           translation ',num2str(Tne(1,4)/2),' ',num2str(Tne(2,4)/2),' ',num2str(Tne(3,4)/2),NL,...
'           children',...
'            [',NL,...
'             Shape',NL,...
'             {',NL,...
'              appearance Appearance',NL,'{',NL,'material Material ',NL,'{',NL,'diffuseColor 9.000001e-2 0.319999 0.444999',NL,'}',NL,'}',NL,...
'              geometry Cylinder',NL,'{',NL,'height ', num2str(sqrt(Tne(1,4)^2+Tne(2,4)^2+Tne(3,4)^2)),NL,'radius 0.03',NL,'}',NL,...
'              }',NL,...
'             ]',NL,...
'            }',NL,...
'DEF EndEffector_base Transform',NL,...
'  {',NL...
'  translation ',num2str(Tne(1,4)),' ',num2str(Tne(2,4)),' ',num2str(Tne(3,4)),NL,...
'  rotation ',num2str(r_vect(1)),' ',num2str(r_vect(2)),' ',num2str(r_vect(3)),' ',num2str(rot),' ',NL,...
'  children',NL,...
'    [',NL]);
    
insert_axis_z('_ee',file_fun);
insert_axis_y('_ee',file_fun);
insert_axis_x('_ee',file_fun); 
    
fwrite(file_fun,[NL,...   
'     Shape',NL,...
'       {',NL,...
'       appearance Appearance',NL,'{',NL,'material Material',NL,'{',NL,'diffuseColor 0.470000 0.520000 0.780000',NL,'}',NL,'}',NL,...
'       geometry Box',NL,'{',NL,'size 0.100000 0.100000 4.000000e-2',NL,'}',NL,...
'       }',NL,...
'      DEF EndEffector_Jaw_1 Transform',NL,...
'       {',NL,...
'       rotation -0.5774 0.5774 -0.5774 4.1888',NL,...
'       translation 0 -4.000000e-2 3.000000e-2',NL,...
'        children',NL,...
'         [',NL,...
'          Shape',NL,...
'           {',NL,...
'           appearance Appearance',NL,'{',NL,'material Material',NL,'{',NL,'diffuseColor 0.470000 0.520000 0.780000',NL,'}',NL,'}',NL,...
'           geometry Box',NL,'{',NL,'size 0.100000 0.100000 2.000000e-2',NL,'}',NL,...
'           }',NL,...
'         ]',NL,...
'       }',NL,...
'      DEF EndEffector_Jaw_2 Transform',NL,...
'       {',NL,...
'       rotation -0.5774 0.5774 -0.5774 4.1888',NL,...
'       translation 0 4.000000e-2 3.000000e-2',NL,...
'        children',NL,...
'         [',NL,...
'          Shape',NL,...
'           {',NL,...
'           appearance Appearance',NL,'{',NL,'material Material',NL,'{',NL,'diffuseColor 0.470000 0.520000 0.780000',NL,'}',NL,'}',NL,...
'           geometry Box',NL,'{',NL,'size 0.100000 0.100000 2.000000e-2',NL,'}',NL,...
'           }',NL,...
'         ]',NL,...
'       }',NL,...
'    ]',NL,...
'  }',NL]);

end

%% rotation matrix 2 axis angle
function [r,theta] = rot2aa(R)

theta = acos(0.5*(R(1,1)+R(2,2)+R(3,3)-1));

if theta == 0 || theta == pi
    r = [0;0;0];
else
r = 0.5*inv((sin(theta)))*[R(3,2)-R(2,3) ; R(1,3)-R(3,1) ; R(2,1)-R(1,2)];
end

end