#!/usr/bin/env python

"""

DOCUMENTATION:

    The purpose of this module is to automate the procedure of initializing a
    general project.
    This includes copying the structure of the indicated source directory for
    the report based on what format (greek - english) do we want the report to
    have into the specified destination directory

"""

import os
import sys
import time
from shutil import copytree

from sup_funs import print_

#  INITIALIZATION PARAMETERS

init_dir =  os.getcwd()
dir_dst = os.getcwd()  # change this #todo
name = 'Project' # to change by user
if name not in os.listdir(dir_dst):
    os.mkdir(name)
os.chdir(name)

# dirnames
latex_src = '/Users/nick/local/latex_extensions'
latex_version = 'EN'
latex_ver_dict = {'EN': 'template_EN',
                  'GR': 'template_GR'}


print_('Initializing project in {}'.format(dir_dst))

dirs2create = {'Archive': None, 'Material': ['Books', 'Articles'],
               'Presentation': ['images', 'drafts']}

# top-level directories
for dir_ in dirs2create.keys():
    os.mkdir(dir_)

# for each dir create the subdirs
for topdir in dirs2create:
    subdirs = dirs2create[topdir]
    if subdirs is not None:
        print('Populating {}'.format(topdir))
        for subdir in subdirs:
            os.mkdir("".join([topdir, os.sep, subdir]))

# REPORT FOLDER
msg = 'Building the "Report" directory\n\tPopulating with {} template'.format(
    latex_version)
print_(msg)
latex_dir = "".join([latex_src, os.sep, latex_ver_dict[latex_version]])
copytree(latex_dir, 'Report')



# touch the necessary files
files2touch = ['word_db', 'abbreviations', 'todo', 'readme']

now = time.strftime("%c")
for fname in files2touch:
    with open("".join([fname, '.txt']), 'w') as f:
        msg = '{}: Autogenerated by nickkouk - {}'.format(fname, now)
        f.write(msg)
        print('Created {}'.format("".join([fname, '.txt'])))

# EXITING ACTIONS

os.chdir(init_dir)
